# Use Ubuntu 24.04 as the base image
FROM ubuntu:24.04

WORKDIR /home/ubuntu

ADD ./install.sh ./install.sh

# Set the default command to open an interactive bash shell
CMD ["bash","./install.sh"]