
const char* ul_error_strings[] = {
    "No error has occurred",
    "Unhandled internal exception",
    "Invalid device handle",
    "This function cannot be used with this device",
    "Insufficient permission to access this device",
    "USB interface is already claimed",
    "Device not found",
    "Device not connected or connection lost",
    "Device no longer responding",
    "Buffer too small for operation",
    "Invalid buffer",
    "Invalid memory type",
    "Invalid memory region",
    "Invalid range",
    "Invalid analog input channel specified",
    "Invalid input mode specified",
    "A background process is already in progress",
    "Invalid trigger type specified",
    "FIFO overrun, data was not transferred from device fast enough",
    "FIFO underrun, data was not transferred to device fast enough",
    "Operation timed out",
    "Invalid option specified",
    "Invalid sampling rate specified",
    "Sample count cannot be greater than FIFO size for BURSTIO scans",
    "Configuration not supported",
    "Invalid configuration value",
    "Invalid analog input channel type specified",
    "ADC overrun occurred",
    "Invalid thermocouple type specified",
    "Invalid unit specified",
    "Invalid queue size",
    "Invalid config item specified",
    "Invalid info item specified",
    "Invalid flag specified",
    "Invalid sample count specified",
    "Internal error",
    "Invalid coupling mode",
    "Invalid sensor sensitivity",
    "Invalid IEPE mode",
    "Invalid channel queue specified",
    "Invalid gain queue specified",
    "Invalid mode queue specified",
    "FPGA file not found",
    "Unable to read FPGA file",
    "FPGA not loaded",
    "Invalid argument",
    "Minimum slope value reached",
    "Maximum slope value reached",
    "Minimum offset value reached",
    "Maximum offset value reached",
    "Invalid port type specified",
    "Digital I/O is configured incorrectly",
    "Invalid bit number",
    "Invalid port value specified",
    "Invalid re-trigger count",
    "Invalid analog output channel specified",
    "Invalid D/A output value specified",
    "Invalid timer specified",
    "Invalid frequency specified",
    "Invalid duty cycle specified",
    "Invalid initial delay specified",
    "Invalid counter specified",
    "Invalid counter value specified",
    "Invalid DAQ input channel type specified",
    "Invalid number of channels specified",
    "Invalid counter register specified",
    "Invalid counter measurement type specified",
    "Invalid counter measurement mode specified",
    "Invalid debounce time specified",
    "Invalid debounce mode specified",
    "Invalid edge detection mode specified",
    "Invalid tick size specified",
    "Invalid DAQ output channel type specified",
    "No connection established",
    "Invalid event type specified",
    "An event handler has already been enabled for this event type",
    "Invalid event parameter specified",
    "Invalid callback function specified",
    "Invalid memory address",
    "Memory access denied",
    "Device is not available at time of request",
    "Re-trigger option is not supported for the specified trigger type",
    "This function cannot be used with this version of the device",
    "This digital operation is not supported on the specified port",
    "Invalid digital port index specified",
    "Temperature input has open connection",
    "Device is not ready to send data",
    "Pacer overrun, external clock rate too fast.",
    "Invalid trigger channel specified",
    "Invalid trigger level specified",
    "Invalid channel order",
    "Temperature input is out of range",
    "Trigger threshold is out of range",
    "Incompatible firmware version, firmware update required",
    "Specified network interface is not available or disconnected",
    "Invalid host specified",
    "Invalid port specified",
    "Network interface used to obtain the device descriptor not available or disconnected",
    "Network connection failed",
    "Invalid connection code",
    "Connection code ignored",
    "Network device already in use",
    "Invalid network frame  ",
    "Network device did not respond within expected time",
    "Data socket connection failed",
    "One or more bits on the specified port are used for alarm",
    "The specified bit is used for alarm",
    "Common-mode voltage range exceeded",
    "Network buffer overrun, data was not transferred from buffer fast enough",
    "Invalid network buffer"
};